name: solar-system-workflow

on:
    workflow_dispatch:
    push:
        branches:
             - main
             - 'feature/*'
env:
  MONGO_URI: 'mongodb+srv://supercluster.d3jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MANGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MANGO_PASSWORD }}

jobs:
    unit-testing:
        name: unit-testing
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            - name: Setups+-Nodejs version
              uses: actions/setup-node@v3
              with: 
                node-version: 22
            - name: Insgtall dependencies
              run: npm install
            - name: Unit testing
              run: npm test