name: woflow-learn

on:
    workflow_dispatch:

jobs:
    context_github:
        runs-on: ubuntu-latest
        steps:
            - name: Github context
              run: |
                   echo ${{tojson(job)}}